// <auto-generated />
namespace SendBroadcast.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddingColumnMessageType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingColumnMessageType));
        
        string IMigrationMetadata.Id
        {
            get { return "201710091346048_AddingColumnMessageType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
